### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by thisfardi** [reacto11mecha/nesbaen#3]
![image](https://user-images.githubusercontent.com/38723240/151050221-40b82098-7d53-4b77-8d2d-ed563aa0c8ac.png)
padahal sdh ada foldernya dan file GURU.xlsx nya bang. mhon solusinya bang, terima kasih _/\_

**Comment by reacto11mecha** [comment]
Boleh tau versi node sama npm, sama os yang dipake ? Saya masih disekolah, nanti pulang saya cek lagi

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/151165296-47e8f45a-90f4-4d07-b0a4-1f889f2cd91d.png)

**Comment by reacto11mecha** [comment]
Sori sori late reply, langkah langkah terjadinya error dijelasin juga dong, biar errornya bisa dihasilin di laptop saya

**Comment by thisfardi** [comment]
npm start 
muncul error digambar ini pak
![image](https://user-images.githubusercontent.com/38723240/151527567-72983c90-a495-426b-bbae-040fb26c269e.png)

padahal folder 'sensitive' sdh dibuat sama file 'GURU.xlsx' nya jg ada difolder 'sensitive' pak. tp ketika dijalanin Error: ENOENT: no such file or directory.

mohon solusinya pak. terima kasih

**Comment by reacto11mecha** [comment]
> npm start muncul error digambar ini pak ![image](https://user-images.githubusercontent.com/38723240/151527567-72983c90-a495-426b-bbae-040fb26c269e.png)
> 
> padahal folder 'sensitive' sdh dibuat sama file 'GURU.xlsx' nya jg ada difolder 'sensitive' pak. tp ketika dijalanin Error: ENOENT: no such file or directory.
> 
> mohon solusinya pak. terima kasih

Boleh tau stacktrace nya nggak ? Dari file mana line berapa errornya ?

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/151652590-77ab2ee3-d3ad-4aef-8be1-02d92bb867ff.png)
ini pak

**Comment by reacto11mecha** [comment]
Coba kak @thisfardi, checkout ke branch terbaru saya yang `fix/path-compatibility`.

```sh
git remote add upstream git@github.com:reacto11mecha/nesbaen.git
git fetch upstream
git checkout --track upstream/fix/path-compatibility
```

Jangan lupa install ulang lagi packagenya. soalnya ada update. Abis tu jalanin lagi
```sh
npm install
npm start
```

Jangan lupa bilang ya kak kalo dah jalan, di laptop ku jalan (linux) sebagaimana mestinya, tinggal di windows aja. Biar pr #4 bisa di merge ke main.

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/152494394-6284ad92-5cd3-49f6-a6a7-88f7c1618d49.png)
error baru om
maaf baru online

**Comment by reacto11mecha** [comment]
> ![image](https://user-images.githubusercontent.com/38723240/152494394-6284ad92-5cd3-49f6-a6a7-88f7c1618d49.png) error baru om maaf baru online

Perasaan saya di baris 8 penamaannya nggak kayak begitu, coba di checkout dulu, abis tu coba cek sama nggak sama pr #4.
File https://github.com/reacto11mecha/nesbaen/blob/3db8397fa2a3376b3d0ca94a1e9452695e24e0a8/utils/readALotXLSX.js

```sh
git checkout .
```

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/152802046-9ad92410-8aa4-46cb-81b4-ade5b03bdd44.png)
keren pak bisa, tp sekarang error baru pak `Guru bernama ${reformatted.name} namanya salah, coba di cek kembali apakah nama tersebut sudah benar. File: ${file}`
                                                                                     
                                ^

ReferenceError: file is not defined

padahal pake GURU.xlsx di folder example, sy cb rename nama lain error pak.

![image](https://user-images.githubusercontent.com/38723240/152803820-f649081a-312d-44d7-8e56-89f1b71376a4.png)
klo sy rename bgni skrng yg error `Siswa bernama ${reformatted.name} namanya salah, coba di cek kembali apakah nama tersebut sudah benar. File: ${file}`
                                                                                     
                                   ^

ReferenceError: file is not defined

![image](https://user-images.githubusercontent.com/38723240/152804141-a39f434d-656b-4510-9100-873b1f8c350b.png)
ini sy rename NAMA GURU jadi ALEXA malah error, tp klo NAMA GURU bawahnya NAMA GURU yg error NAMA SISWA.

mohon solusinya pak. terima kasih _/\_

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/152825161-d2a53b24-d6ce-44c9-8187-ed509917d5ab.png)
file xlsx GURU dan X BAHASA
![image](https://user-images.githubusercontent.com/38723240/152825616-b17bb9bf-f60b-45a8-a34b-82edc81dce3f.png)
TypeError: item is not iterable

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/152832177-221d9e5c-eefc-4058-b4c8-1bbbe3144f8d.png)

**Comment by thisfardi** [comment]
![image](https://user-images.githubusercontent.com/38723240/152837366-1e0d2cc3-458b-4d5a-9a84-71499f452664.png)
![image](https://user-images.githubusercontent.com/38723240/152837458-fefe9ba9-bb3a-47f7-911c-43abf67a4866.png)
![image](https://user-images.githubusercontent.com/38723240/152837534-6682585e-b80e-4852-8998-c831505d4267.png)
work pak bot nya sy coba ganti line 11 jadi 'penampung = [item];'

**Comment by reacto11mecha** [comment]
Atau nggak gini deh, saya merge #5 terus di clone ulang aja

**Comment by reacto11mecha** [comment]
Saya reopen lagi

**Comment by thisfardi** [comment]
sdh running pak solved masalah [Error: ENOENT: no such file or directory](https://github.com/reacto11mecha/nesbaen/issues/3#)
#3 ini
terima kasih pak _ / \ _

**Comment by reacto11mecha** [comment]
Hmm okey

**Comment by thisfardi** [comment]
pak insert data Excel ke DB Mongo nya cm bisa 1x yh? ketika tambah data di Excelnya running ulang bot nya dia gk nambah di cek DB Mongo?
sama code ini 
```
default:
      await client.simulateTyping(message.from, true);
      await client.reply(
        from,
        command.length > 0
          ? `Tidak ada perintah yang bernama '${command}'`
          : botInfo,
        id,
        true
      );
      await client.simulateTyping(message.from, false);
  }
```
cuma di wa nya cuma kebaca ini codenya `Tidak ada perintah yang bernama '${command}'` jadi hasilnya di wa cuma Tidak ada perintah yang bernama 'x'
yg ini 
```
: botInfo,
        id,
        true
```
gk kebaca dia.
mohon solusinya pak
terima kasih _ / \ _

**Comment by reacto11mecha** [comment]
Coba open issue nya di issue yang baru deh, takut tenggelem kalo di bahas disini

**Comment by thisfardi** [comment]
oke pak
