### ISSUE TITLE
Error DEPLOY HEROKUAPP

### ISSUE THREAD

**Issue by thisfardi** [reacto11mecha/nesbaen#5]
![image](https://user-images.githubusercontent.com/38723240/152527406-2683195e-783b-40f7-989e-0540e588b0d2.png)

**Comment by reacto11mecha** [comment]
Hm kayaknya PR #2 ga lengkap, ya udah nanti saya cek lagi dari yang open pr nya

**Comment by reacto11mecha** [comment]
Apa udah aman di herokunya ?

**Comment by thisfardi** [comment]
sudah pak mantap, thanks pak _ / \  _
